name: E2E Tests

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Frontend Repository
      uses: actions/checkout@v2

    - name: Checkout E2E Repository
      uses: actions/checkout@v2
      with:
        repository: JoaoVitorSantDrade/cypress-cabeceira
        ref: main 

    - name: Pull Cypress Docker image
      run: docker pull --quiet cypress/included:12.12.0

    - name: Run E2E Tests in Docker
      run: docker run -v $(pwd):/e2e -w /e2e cypress/included:12.12.0
